### ISSUE TITLE
Program "IDG" likely wrong - More programs exist

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#100]
We don't have gene sets or signatures generated by the IDG. Also, the LINCS program is missing, so having only IDG is weird.

These libraries can be associated with the following programs:

Achilles_fitness_decrease - Achilles
Achilles_fitness_increase - Achilles

Allen_Brain_Atlas_down - Allen_Brain_Atlas
Allen_Brain_Atlas_up - Allen_Brain_Atlas

DepMap_WG_CRISPR_Screens_Broad_CellLines_2019 -  DepMap
DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019 - DepMap

ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X - ENCODE
ENCODE_Histone_Modifications_2013 - ENCODE
ENCODE_Histone_Modifications_2015 - ENCODE
ENCODE_TF_ChIP-seq_2014 - ENCODE
ENCODE_TF_ChIP-seq_2015 - ENCODE

Epigenomics_Roadmap_HM_ChIP-seq - Epigenomics_Roadmap

GTEx_Tissue_Sample_Gene_Expression_Profiles_down - GTEx
GTEx_Tissue_Sample_Gene_Expression_Profiles_up - GTEx

LINCS_L1000_Chem_Pert_down - LINCS
LINCS_L1000_Chem_Pert_up - LINCS
LINCS_L1000_Kinase_Perturbations_down - LINCS
LINCS_L1000_Kinase_Perturbations_up - LINCS
LINCS_L1000_Ligand_Perturbations_down - LINCS
LINCS_L1000_Ligand_Perturbations_up - LINCS

MGI_Mammalian_Phenotype_2013 - KOMP
MGI_Mammalian_Phenotype_2017 - KOMP
MGI_Mammalian_Phenotype_Level_3 - KOMP
MGI_Mammalian_Phenotype_Level_4 - KOMP

NURSA_Human_Endogenous_Complexome - NURSA

**Comment by jeevangelista** [comment]
Updated database.
