### ISSUE TITLE
SigCom-LINCS: 7 types of what?

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#131]

**Comment by jeevangelista** [comment]
Hi Avi,
Here are the values of these types from the database:

Transcription profiling | 43
Kinase binding | 31
Proteomic profiling | 13
Epigenomics | 6
Models derived from other datasets | 2
Analysis of models | 1
Transcriptomics | 1

Do you have any suggestions as to what to name them? Or should I even include them on the counts?
