### ISSUE TITLE
Improve documentation on how to run locally

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#17]
This step is missing...

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! signature-commons-ui@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the signature-commons-ui@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Avi Ma'ayan\AppData\Roaming\npm-cache\_logs\2018-12-01T20_36_43_977Z-debug.log

See for example good instructions listed here https://github.com/MaayanLab/LINCS

**Comment by AviMaayan** [comment]
This is mostly because I was trying to run it on Windows... It works on the Mac...

**Comment by AviMaayan** [comment]
That worked... the -g was missing... I now get: 
npm WARN deprecated highcharts-more@0.1.7: this package has been deprecated, just import modules from the highcharts folder
but this is only an issue in windows... on the mac everything works fine...

**Comment by u8sand** [comment]
I imagine it would still work despite the warning but maybe not
