### ISSUE TITLE
The list of returned results is not informative enough

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#19]
The icon of the source module is good, but the colored bar does not give much intuitive information about the signature.

I suggest replacing the colored bar with a signature description based on the original names that we have in Enrichr (L1000 and CREEDS signatures should be modeled to follow the same structure)... So the most important metadata elements for each signature should be shown...

For L1000 signatures:

Assay: L1000; Batch: CPC006; Cell-line: PC3; Time point: 24H; Perturbation BRD-K35716340; Concentration: 12.0

For CREEDS:

Assay: Microarray; Drug name: troglitazone; DrugBank ID: DB00197; Organism: rat; GEO Accession: GSE21329; CREEDS ID: sample 2832

Additional metadata such as the UUID can be downloaded and/or expanded... For each signature type, the most important metadata elements should be shown...

**Comment by u8sand** [comment]
I can force this information for now, but in the future we'll need to specify in the schema itself what is *important* or *not*
