### ISSUE TITLE
Remove Enrichr buttons from the results of the signature search

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#38]

**Comment by u8sand** [comment]
You mean from a metadata search? Or remove it as a resource (from both resource and a resource selector)

I'll like to note that the Enrichr Resource is made of the following libraries:

- Enrichr Libraries Most Popular Genes
- Enrichr Submissions TF-Gene Coocurrence

In which case it may actually make sense to keep it; let me know

**Comment by AviMaayan** [comment]
The two libraries can stay but Enrichr now is downgraded into a resource... I meant this tag (in red square) in the 
![enrichr](https://user-images.githubusercontent.com/12749033/51045266-2ebb9f80-1591-11e9-9523-27fc9e2487c4.png)
attachment.
