### ISSUE TITLE
LINCS L1000 icon is too transparent... Also, the old CMAP icon does not look right

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#61]

**Comment by jeevangelista** [comment]
Hi!

I've used the icon from the [old cmap website](https://portals.broadinstitute.org/cmap/). Should I use the icon of Broad instead? Thanks!

(Pics for reference)
icon:
<img src="https://user-images.githubusercontent.com/1305807/51712119-cc848500-1ffb-11e9-81eb-55ada2ef44c4.png">
cmap website screenshot:
<img width="619" src="https://user-images.githubusercontent.com/1305807/51712129-d0b0a280-1ffb-11e9-85e7-096bb5e24f13.png">

**Comment by AviMaayan** [comment]
Yes.

Best,

Avi
