### ISSUE TITLE
Change text in the signature search page

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#79]
One Tailed -> Get Set or Full Signature
Two Tailed* -> Up and Down Gene Sets

**Comment by u8sand** [comment]
These work with any set of entities realistically, not just genes.

**Comment by AviMaayan** [comment]
Right now we only have genes... The problem is that it is not descriptive enough for people to understand what to do and the two tailed one tailed is not standard terminology...
