### ISSUE TITLE
Integrate with the signature search UI developed by Alex and make them look like one app

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#9]

**Comment by u8sand** [comment]
I'm thinking I can create a *cart* page which looks similar to a single column of alex's app--then the user would provide the gene list and we could make the query and return the results like they are shown on the homepage but with p-value/stuff added

**Comment by AviMaayan** [comment]
I would create a menu that contains the following 4 main sections:

Metadata Search (the one you have now)
Signature Search (the one to submit lists and signatures)
Collections of Signatures (lists the collections available with some description and stats)
Upload a Collection (allows users to upload a new collection such as Enrichr, CREEDS etc., this can be a placeholder for now)
