### ISSUE TITLE
Replace text on new landing page

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons-ui#97]
Replace:
Explore our collection of signatures extracted from an ever-growing number of resources
With:
Signature Commons contains a extensive collection of well-annotated gene-sets and signatures 

Replace:
Search across a wide-array of biological information
With:
Search across a broad gathering of perturbations

**Comment by AviMaayan** [comment]
Explore an extensive collection of well-annotated gene-sets and signatures

**Comment by jeevangelista** [comment]
541ea9d4b0984ed6c0243b703f8078df7d51e128
